version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gh-actions"

  - package-ecosystem: "npm"
    directory: "client"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        applies-to: version-updates
        dependency-type: development
      production-dependencies:
        applies-to: security-updates
        dependency-type: production
    commit-message:
      prefix: "npm(frontend)"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        applies-to: version-updates
        dependency-type: development
      production-dependencies:
        applies-to: security-updates
        dependency-type: production
    commit-message:
      prefix: "npm(backend)"
