name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: /server
        run: npm ci

      - name: Install dependencies
        working-directory: /client
        run: npm ci

      - name: Lint source
        working-directory: /server
        run: npm run lint

      - name: Lint source
        working-directory: /client
        run: npm run lint

      - name: Build
        working-directory: /server
        run: npm run build

      - name: Build
        working-directory: /client
        run: npm run build
